name: Primeiro workflow

on:
  push: 
    branches: 
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
jobs:
  job1:
    name: Primeira tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1
        run: echo "executando o primeiro passo."
      - name: Passo 2
        run: echo "executando passo 2."
      - name: Passo 3
        run: echo "executando passo 3."
 
  job2:
    name: Segunda tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 4
        run: echo "executando passo 4."
      - name: Passo 5
        run: echo "executando passo 5."
      - name: Passo 6
        run: echo "executando passo 6."
    
